var series =[{“id”:1,”nome”:"Arrow","poster":"./posters/arrow.jpg",”categoria”:”Ação e aventura”},
		{“id”:1,”nome”:"Beauty & the beast","poster":"./posters/b&b.jpg",”categoria”:”Ação e aventura”},
		{“id”:1,”nome”:"Bitten","poster":"./posters/bitten.jpg",”categoria”:”Drama/Ficção”},
		{“id”:1,”nome”:"Bates Motel","poster":"./posters/bm.jpg",”categoria”:”Drama/Suspense”},
		{“id”:1,”nome”:"Castle","poster":"./posters/castle.jpg", “categoria”:”Policial/”Ação”},
		{“id”:1,”nome”:"Daredevil","poster":"./posters/dd.jpg",”categoria”:”Ação/Ficção”},
		{“id”:1,”nome”:"Dexter","poster":"./posters/dexter.jpg",”categoria”:”Drama”},
		{"id:1,”nome”:"Flash","poster":"./posters/flash.jpg",”categoria”:"Ação/Aventura”},
		{"id”:1,”nome”:"Grey's Anatomy","poster":"./posters/ga.jpg","categoria":”Drama”},
		{“id”:1,”nome”:"Game of Thrones","poster":"./posters/got.jpg","categoria":”Ação/Drama”},
		{“id”:1,”nome”:"Gotham","poster":"./posters/gotham.jpg",”categoria”:”Ação/Aventura”},
		{“id”:1,”nome”:"Hannibal","poster":"./posters/hannibal.jpg",”categoria”:”Suspense”},
		{“id”:1,”nome”:"How I met your mother","poster":"./posters/himym.png",”categoria”:”Comédia”},
		{“id”:1,”nome”:"House","poster":"./posters/house.jpg",”categoria”:”Drama/Comédia”},
		{“id”:1,”nome”:"Jessica Jones","poster":"./posters/jj.jpg",”categoria”:”Ação/Drama”},
		{“id”:1,”nome”:"Narcos","poster":"./posters/narcos.jpg",”categoria”:”Drama”},
		{“id”:1,”nome”:"Orange is the new black","poster":"./posters/oitn.jpg",”categoria”:”Comédia/Drama”},
		{“id”:1,”nome”:"Once upon a time","poster":"./posters/ouat.jpg",”categoria”:”Drama/Ação/Fantasia”},
		{“id”:1,”nome”:"Penny Dreadful","poster":"./posters/pd.jpg",”categoria”:”Suspense/Terror”},
		{“id”:1,”nome”:"Revenge","poster":"./posters/revenge.jpg",”categoria”:”Drama”},
		{“id”:1,”nome”:"Sense8","poster":"./posters/s8.jpg",”categoria”:Ficção/Ação”},
		{“id”:1,”nome”:"Salem","poster":"./posters/salam.jpg",”categoria”:”Drama/Suspense/Terror”},
		{“id”:1,”nome”:"Scandal","poster":"./posters/scandal.jpg",”categoria”:”Drama”},
		{“id”:1,”nome”:"Scream","poster":"./posters/scream.jpg",”categoria”:”Suspense/Terror”},
		{“id”:1,”nome”:"Shadowhunters","poster":"./posters/sh.jpg",”categoria”:”Ficção/Ação”},
		{“id”:1,”nome”:"Sherlock","poster":"./posters/sherlock.jpg",”categoria”:”Drama/Policial”},
		{“id”:1,”nome”:"Smallville","poster":"./posters/Smallville.jpg",”categoria”:”Drama/Ação”},
		{“id”:1,”nome”:"Stranger things","poster":"./posters/st.jpg",”categoria”:”Suspense/Terror/Ação”},
		{“id”:1,”nome”:"Supernatural","poster":"./posters/supernatural.jpg",”categoria”:”Ficção/Suspense”},
		{“id”:1,”nome”:"Thirteen Reasons why","poster":"./posters/trw.jpg",”categoria”:”Drama”},
		{“id”:1,”nome”:"Teen Wolf","poster":"./posters/tw.jpg",”categoria”:”Ação/Ficção”},
		{“id”:1,”nome”:"The Walking Dead","poster":"./posters/twd.jpg",”categoria”:Ficção/Terror”},
		{“id”:1,”nome”:"Vikings","poster":"./posters/vikings.jpg",”categoria”:”Ação/Aventura”}

];