var series =[{"nome":"Arrow","poster":"./posters/arrow.jpg"},
			{"nome":"Beauty & the Beast","poster":"./posters/b&b.jpg"},
			{"nome":"Bitten","poster":"./posters/bitten.jpg"},
			{"nome":"Bates Motel","poster":"./posters/bm.jpg"},
			{"nome":"Castle","poster":"./posters/castle.jpg"},
			{"nome":"Daredevil","poster":"./posters/dd.jpg"},
			{"nome":"Dexter","poster":"./posters/dexter.jpg"},
			{"nome":"Flash","poster":"./posters/flash.jpg"},
			{"nome":"Grey's Anatomy","poster":"./posters/ga.jpg"},
			{"nome":"Game of Thrones","poster":"./posters/got.jpg"},
			{"nome":"Gotham","poster":"./posters/gotham.jpg"},
			{"nome":"Hannibal","poster":"./posters/hannibal.jpg"},
			{"nome":"How I met your mother","poster":"./posters/himym.png"},
			{"nome":"House","poster":"./posters/house.jpg"},
			{"nome":"Jessica Jones","poster":"./posters/jj.jpg"},
			{"nome":"Narcos","poster":"./posters/narcos.jpg"},
			{"nome":"Orange is the new black","poster":"./posters/oitn.jpg"},
			{"nome":"Once upon a time","poster":"./posters/ouat.jpg"},
			{"nome":"Penny Dreadful","poster":"./posters/pd.jpg"},
			{"nome":"Revenge","poster":"./posters/revenge.jpg"},
			{"nome":"Sense8","poster":"./posters/s8.jpg"},
			{"nome":"Salem","poster":"./posters/salam.jpg"},
			{"nome":"Scandal","poster":"./posters/scandal.jpg"},
			{"nome":"Scream","poster":"./posters/scream.jpg"},
			{"nome":"Shadowhunters","poster":"./posters/sh.jpg"},
			{"nome":"Sherlock","poster":"./posters/sherlock.jpg"},
			{"nome":"Smallville","poster":"./posters/Smallville.jpg"},
			{"nome":"Stranger things","poster":"./posters/st.jpg"},
			{"nome":"Supernatural","poster":"./posters/supernatural.jpg"},
			{"nome":"Thirteen Reasons why","poster":"./posters/trw.jpg"},
			{"nome":"Teen Wolf","poster":"./posters/tw.jpg"},
			{"nome":"The Walking Dead","poster":"./posters/twd.jpg"},
			{"nome":"Vikings","poster":"./posters/vikings.jpg"},
			{"nome":"Zoo","poster":"./posters/zoo.jpg"}
];